### PR TITLE
feat: Use auto_image transform from Filestack

### LINKED ISSUE #17: WebP support check doesn't pass for Firefox
The current implementation of the webp check doesn't work for Firefox, although it has had support since version 65: https://github.com/GraphCMS/graphcms-image/blob/master/src/index.js#L23-L37

Why? Firefox doesn't support webp in data-urls yet. See https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toDataURL

> Chrome also supports the image/webp type.

- Relevant bug report: https://bugzilla.mozilla.org/show_bug.cgi?id=1559743
- Vercel handles check on server side: https://github.com/vercel/next.js/blob/canary/packages/next/next-server/server/image-optimizer.ts#L46
- Alternate approach (async!): https://stackoverflow.com/a/54120785/684032

Did you purposely choose the sync approach? How about handling the detection server-side? I'm not sure if the media assets server GraphCMS uses is open source and/or supports this!?

Thanks for making GraphCMS!

### PR DESCRIPTION
**Pull request by leomelzer**
This serves WebP to supported browsers

Closes #17

### CODE REVIEW

**Comment by notrab** [comment]
Nice @leomelzer - I just ran this and can confirm the intended output.

I'm hoping to add some automated publishing to this repo since it's been stale for quite a bit, so once I add that, I'll merge, and release.

**Comment by moritzjacobs** [comment]
I would love this to be merged as well :)

**Review by moritzjacobs — APPROVED** [review]

**Comment by notrab** [comment]
@hmeissner are you ok to cut a new release if you merge this?

**Comment by leomelzer** [comment]
I've went ahead and created a PR for introducing semantic-release based on your other configuration in gatsby-source-graphcms. Maybe that eases the process here.

**Pull request merged**
